- name: Configure new machine
  hosts: controlmachine
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        upgrade: true
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
  - name: Ping test
    ansible.builtin.ping:

  - name: Print message
    ansible.builtin.debug:
      msg: "Install Qtile and other packages for user {{ user }}."
  
  - include_tasks: tasks/core-utils.yml
  - include_tasks: tasks/python.yml
  - include_tasks: tasks/node.yml
  - include_tasks: tasks/neovim.yml
  - include_tasks: tasks/alacritty-install.yml
  - include_tasks: tasks/brave.yml
  - include_tasks: tasks/rust.yml
  - include_tasks: tasks/git-config.yml
  - include_tasks: tasks/fonts.yml
  - include_tasks: tasks/configure-neovim-tmux.yml
  - include_tasks: tasks/qtile.yml
  - include_tasks: tasks/vscode.yml
