- name: Add allacritty ppa (ppa:aslatter/ppa)
  become: true
  apt_repository:
    repo: ppa:aslatter/ppa
    state: present
    update_cache: true
  tags:
    - install
    - core
    - terminal

- name: Install the Alacritty terminal
  become: true
  apt:
    name: alacritty
  tags:
    - install
    - core
    - terminal

- name: Ensure alacritty directory exists
  ansible.builtin.file:
    path: "{{ home }}/.config/alacritty"
    state: directory
    mode: '0755'

- name: Download alacritty.yml
  ansible.builtin.copy:
    src: files/alacritty.yml
    dest: "{{ home }}/.config/alacritty/alacritty.yml"
  tags:
    - install
    - core
    - terminal

