- name: Download Brave browser keyring
  become: true
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - install
    - brave

- name: Add brave ppa
  become: true
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - install
    - brave

- name: Install Brave Browser
  become: true
  apt:
    update_cache: true
    name: brave-browser
  tags:
    - install
    - brave
