[colors.bright]
black = "0x21242b"
blue = "0x2257a0"
cyan = "0x5699af"
green = "0x4db5bd"
magenta = "0xa9a1e1"
red = "0xda8548"
white = "0x5b6268"
yellow = "0xd19a66"

[colors.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[env]
TERM = "xterm-256color"

[font]
size = 6.0

[font.normal]
family = "MesloLGM Nerd Font Mono"

[window.padding]
x = 5
y = 5
